server:
  port: 8091
spring:
  application:
    name: neil-project-user
  profiles:
    active: test

  datasource:
    url: jdbc:mysql://localhost:3306/neil?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 12345678

neil:
  myth:
    enabled: true
    myth-db-config:
      url: jdbc:mysql://localhost:3306/neil?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: 12345678
    mq:
      rocketmq:
        consumer-enabled: false
        consumer-topic: MYTH-USER
        consumer-group: MYTH-USER-GROUP

rocketmq:
  name-server: localhost:9876

knife4j:
  enable: true
  basic:
    enable: true
    username: neil
    password: 123123123