server:
  port: 8093
spring:
  application:
    name: neil-project-ai
  profiles:
    active: test
  ai:
    ollama:
      chat:
        model: llama3

knife4j:
  enable: true
  basic:
    enable: true
    username: neil
    password: 123123123



