server:
  port: 8093
spring:
  application:
    name: neil-project-ai
  profiles:
    active: test
  ai:
    ollama:
      chat:
        model: llama3
      embedding:
        model: nomic-embed-text
    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        initialize-schema: true
        collection-name: neil-ai

knife4j:
  enable: true
  basic:
    enable: true
    username: neil
    password: 123123123



