server:
  port: 8093
spring:
  application:
    name: neil-project-ai
  profiles:
    active: test

  datasource:
    url: jdbc:mysql://localhost:3306/neil?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 12345678

  data:
    mongodb:
      uri: mongodb://neil_myth:123456@localhost:27017/neil_myth
      auto-index-creation: true

  ai:
    ollama:
      chat:
        model: llama3.1
      embedding:
        model: nomic-embed-text

    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        initialize-schema: true
        collection-name: neil-ai

knife4j:
  enable: true
  basic:
    enable: true
    username: neil
    password: 123123123




