server:
  port: 8092
spring:
  application:
    name: neil-project-goods
  profiles:
    active: test

  data:
    mongodb:
      uri: mongodb://neil_myth:123456@localhost:27017/neil_myth
      auto-index-creation: true

neil:
  myth:
    enabled: true
    repository-support: mongodb
    mq:
      rocketmq:
        consumer-enabled: true
        consumer-topic: MYTH-GOODS
        consumer-group: MYTH-GOODS-GROUP
    myth-mongo-db-config:
      mongo-db-name: neil_myth
      mongo-url: mongodb://neil_myth:123456@localhost:27017/neil_myth


rocketmq:
  name-server: localhost:9876