server:
  port: 8079
spring:
  application:
    name: neil-project-pc-bff
  profiles:
    active: test
knife4j:
  enable: true
  basic:
    enable: true
    username: neil
    password: 123123123


jwt:
  key:
    public: classpath:jwt/public.key
    private: classpath:jwt/private.key
