server:
  port: 8090
spring:
  application:
    name: neil-project-order
  profiles:
    active: test

  datasource:
    url: jdbc:mysql://rm-bp1g2h039zca3uv80.mysql.rds.aliyuncs.com:3306/yl_drugmall_00?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: tst_tu_2975d79
    password: tst_tu_2975d79_7009ca
    druid:
      initial-size: 1
      max-active: 10
      min-idle: 1
      max-wait: 60000

neil:
  myth:
    enabled: true
    myth-db-config:
      url: jdbc:mysql://rm-bp1g2h039zca3uv80.mysql.rds.aliyuncs.com:3306/yl_drugmall_00?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: tc_dev_2975d79
      password: tc_dev_2975d79_7c9a4d



