server:
  port: 8090
spring:
  application:
    name: neil-project-order
  profiles:
    active: test

  datasource:
    url: jdbc:mysql://localhost:3306/neil?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

neil:
  myth:
    enabled: true
    myth-db-config:
      url: jdbc:mysql://localhost:3306/neil?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
    mq:
      rocketmq:
        producer-enabled: true
        producer-group: MYTH-ORDER


rocketmq:
  name-server: localhost:9876





