server:
  port: 8090
spring:
  application:
    name: neil-project-order
  profiles:
    active: test

  datasource:
    url: XXXXX
    username: XXXXX
    password: XXXXX

neil:
  myth:
    enabled: true
    myth-db-config:
      url: XXXXX
      username: XXXXX
      password: XXXXX



