server:
  port: 8090
spring:
  application:
    name: neil-project-order
  profiles:
    active: test

  datasource:
    url: jdbc:mysql://localhost:3306/neil?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 12345678

neil:
  myth:
    enabled: false
    myth-db-config:
      url: jdbc:mysql://localhost:3306/neil?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: 12345678
    mq:
      rocketmq:
        producer-enabled: false
        producer-group: MYTH-ORDER


rocketmq:
  name-server: localhost:9876

knife4j:
  enable: true
  basic:
    enable: true
    username: neil
    password: 123123123




